---
- name: Adjust vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '{{ es_lb_max_map_count }}'
    state: present
    reload: true

- name: 'Create folders for: {{ es_lb_cont_name }}'
  file:
    path: '{{ es_lb_docker_dir }}/conf'
    state: directory
    user: 1000
    group: adm
    mode: 0775

- name: Create directory for config files
  file:
    path: '{{ es_lb_docker_dir }}/conf/ingest-geoip'
    state: directory

- name: Create config files
  template:
    src: '{{ item }}'
    dest: '{{ es_lb_docker_dir }}/conf/{{ item | basename | replace(".j2", "") }}'
  register: es_lb_config
  with_fileglob:
    - templates/*
