---
- name: Adjust vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '{{ es_lb_max_map_count }}'
    state: present
    reload: true

- name: 'Create folders for: {{ es_lb_cont_name }}'
  file:
    path: '{{ es_lb_docker_dir }}/conf'
    state: directory
    group: 1000
    mode: 0755

- name: Create directory for config files
  file:
    path: '{{ es_lb_docker_dir }}/conf/ingest-geoip'
    state: directory

- name: Fetch available elasticsearch nodes
  uri:
    url: 'http://localhost:8500/v1/catalog/service/elasticsearch?dc={{ es_lb_data_center }}'
  register: es_lb_services

- name: Create config files
  template:
    src: '{{ item }}'
    dest: '{{ es_lb_docker_dir }}/conf/{{ item | basename | replace(".j2", "") }}'
  register: es_lb_config
  with_fileglob:
    - templates/*
