---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ es_lb_cont_name }}'
    consul_services:
      - name: '{{ es_lb_cont_name }}'
        tags: '{{ es_lb_consul_tags }}'
        # we advertise the port with basic auth
        port: '{{ es_lb_api_port }}'
        address: '{{ ansible_local.tinc.vpn_ip }}'
        checks:
          - id: '{{ es_lb_cont_name }}-health'
            name: ElasticSearch Healthcheck
            type: http
            http: 'http://localhost:{{ es_lb_api_port }}/?pretty'
