---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ es_lb_cont_name }}'
    consul_services:
      - name: '{{ es_lb_cont_name }}'
        tags: '{{ es_lb_consul_tags }}'
        # we advertise the port with basic auth
        port: '{{ es_lb_api_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        meta:
            fleet: '{{ env }}.{{ stage }}'
            cluster_port: '{{ es_lb_node_port | string }}'
            cluster_name: '{{ es_lb_cluster_name }}'
        checks:
          - id: '{{ es_lb_cont_name }}-health'
            name: ElasticSearch LB Healthcheck
            type: http
            http: 'http://localhost:{{ es_lb_api_port }}/?pretty'
