---
- name: 'Create compose file'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ es_lb_compose_path }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create containers'
  community.docker.docker_compose_v2:
    project_src: '{{ es_lb_service_path }}'
    recreate:    '{{ compose_recreate }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ es_lb_config.changed | ternary("restarted", compose_state) }}'
